MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
MET -> CAP
CAP -> ETC
CAP -> ETC
CAP -> ETC
CAP -> ETC
CAP -> ETC
ETC -> MET


CAP.shape: circle 
CAP.width: 157 
MET.shape: circle 
MET.width: 100 
ETC.shape: circle 
ETC.width: 124 
